### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Deams51** [VitorCantao/ZeldaBotwClimbingSystem#1]
At the moment the repo does not have a license attached to it. 
It's quite common in the UE4 community to use the MIT license, but regardless code without a license is always making it tricky.
Here's how to add a license to a repository: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

By the way, great job on the article!
I've enjoyed going through it and getting a feel for how you think and approached the problem.
That's the most professional gameplay-related tutorial I've seen in years.

**Comment by VitorCantao** [comment]
Oh yeah, I forgot to include a license. Thank you!

Wow, I really appreciate your kind words, means a lot to me! Thanks a lot again!
